### PR TITLE
Update v0.6

### PR DESCRIPTION
**Pull request by jamwaffles**
Update the `v0.6` with all the non-breaking stuff in master. This was a rebase, followed by an interactive rebase that removes some commits and ruins some others to just make it work.

This has been an _absolute nightmare_. Mostly my fault with the squash-n-merges going on. If we want to do parallel releases (and I very much do), we're going to have to be super careful about how we build on previous breaking changes.

There are probably loads of issues with this PR and I'd be more than happy to throw it away in favour of a better attempt/approach, but here we are for now :)

It goes without saying that this should be a rebase onto `v0.6`, at which point I can do a non-breaking release of `0.6.2` and create a PR to update the changelog in `master`.

### CODE REVIEW

**Comment by rfuest** [comment]
The changes to the `Primitive` crate make some of these changes breaking. It's very unlikely that `Primitive` is implemented externally, but because we haven't prevented this, it's a breaking change IMO.

TBH I would prefer to instead keep the `0.7` development cycle short and release it after #314 and the other primitive changes are merged. Other additions and improvements, like sub images or a fixed `DrawTarget` trait, can be moved to later releases.

**Comment by jamwaffles** [comment]
> The changes to the Primitive crate make some of these changes breaking.

Good point. I can remove it from this PR pretty easily I think - it's just the `fn points()` stuff right?

> TBH I would prefer to instead keep the 0.7 development cycle short and release it after #314 and the other primitive changes are merged.

I don't want to release too many breaking changes in quick succession, hence this (hopefully) non-breaking cherry pick PR for 0.6. It sucks for the growing community around this crate to have to repeatedly fix code, wait for drivers, nag authors, etc when we break stuff all the time. We can also make our lives easier in the future by not bundling up so many changes into one huge 0.6 branch update :)

> ... and release it after #314

Wasn't there some breaking font work (#225, #268, etc) that we wanted to get done as well?

> ... sub images ...

That would be a non-breaking change I think, so could be nicely released in 0.6.

> ... or a fixed DrawTarget trait, can be moved to later releases.

What needs fixing? #263 and #181? Anything else?

**Comment by rfuest** [comment]
> I don't want to release too many breaking changes in quick succession, hence this (hopefully) non-breaking cherry pick PR for 0.6. It sucks for the growing community around this crate to have to repeatedly fix code, wait for drivers, nag authors, etc when we break stuff all the time. We can also make our lives easier in the future by not bundling up so many changes into one huge 0.6 branch update :)

I get your point, but I would prefer to have a shorter development cycle than for `0.6`. Releasing the coordinate system fixes early is important IMO, because otherwise users will have to deal with off by one errors later, which is a bigger pain than an API change that causes a compiler error.

Can we limit `0.7` to primitives, coordinate system, fixing `DrawTarget` and `Transform`? IMO this could be a good compromise.

It would be nice if we could decouple the driver interface to make migration between versions less of a pain. But because we use the primitives in `DrawTarget` I don't think there is a good way to achieve this.

> Good point. I can remove it from this PR pretty easily I think - it's just the `fn points()` stuff right?

That should be all at the moment.

Are you sure that adding `Ellipse` is a good idea? This would introduce more inconsistencies in the primitives module by using different parameters than `Circle` and being of by one for `size = radius * 2`.

> Wasn't there some breaking font work (#225, #268, etc) that we wanted to get done as well?

IMO it would be nice if external font renderers could be used in a similar way than the internal font support. To test this integration we would first need to implement an external renderer, for example for BDFs, but this would delay `0.7` further. If we don't test the integration before the `0.7` release we might have to break the API again in the next version which isn't great either.

> That would be a non-breaking change I think, so could be nicely released in 0.6.

But this could, for example, benefit from the `Points` iterators, which is a breaking change. This was the main reason I started working on the primitives before sub images.

> What needs fixing? #263 and #181? Anything else?

Not quite sure yet, I will need to look into this some more.

**Comment by jamwaffles** [comment]
> I get your point, but I would prefer to have a shorter development cycle than for 0.6

Absolutely, I think that was nearly a year long!

> IMO it would be nice if external font renderers could be used in a similar way than the internal font support.

Not sure what you mean really. There are already external crates with custom font impls. What am I missing?

> Can we limit 0.7 to primitives, coordinate system, fixing DrawTarget and Transform?

Sure, that sounds good. However, I'm concerned that we're artificially spacing out breaking changes over multiple versions. Is there anything you have ideas about that's breaking that you didn't want to get into 0.7? I think people can put up with a couple of breaking releases, but probably not much more than that in quick succession. If we want to redesign the API, let's do it all at once. 

Going back to `master`-only development would certainly cause me less pain - this PR was horrendous to put together, and the end result is still messy. To ease migration from 0.6 to 0.7, perhaps we should release 0.7 alpha versions early (i.e. basically around now)? That would allow us to get the improved coordinate system, etc exercised by end users.

**Comment by rfuest** [comment]
> Not sure what you mean really. There are already external crates with custom font impls. What am I missing?

I meant crates that add support for different font formats, like BDFs. IMO a text using a BDF font should also be drawable using the `embedded_graphics::font::Text` struct.

> Going back to `master`-only development would certainly cause me less pain - this PR was horrendous to put together, and the end result is still messy.

Maybe that's the easiest way for now. But releasing easy fixes like #309 in the 0.6 branch might still be a good idea.

> To ease migration from 0.6 to 0.7, perhaps we should release 0.7 alpha versions early (i.e. basically around now)? That would allow us to get the improved coordinate system, etc exercised by end users.

I would suggest to release the first alpha after #314 is done.

**Comment by jamwaffles** [comment]
> I meant crates that add support for different font formats, like BDFs. IMO a text using a BDF font should also be drawable using the embedded_graphics::font::Text struct.

Yes, that makes a lot of sense. Could we create a `SpritemapFont` (or better name) for the existing bitmap fonts and move all common behaviour to a `Font` trait. Both the builtin bitmaps fonts and BDFs (etc, etc) could implement `Font` as well. Shall I open an issue to discuss this? If you have a better idea please open one instead :)

> Maybe that's the easiest way for now. But releasing easy fixes like #309 in the 0.6 branch might still be a good idea.

I'll get a PR together for #309 and any other small changes so far. I think we can close this PR now - it's too messy and far reaching in its changes. Let me know if you think otherwise.

> I would suggest to release the first alpha after #314 is done.

:+1:

**Comment by rfuest** [comment]
> Yes, that makes a lot of sense. Could we create a `SpritemapFont` (or better name) for the existing bitmap fonts and move all common behaviour to a `Font` trait. Both the builtin bitmaps fonts and BDFs (etc, etc) could implement `Font` as well. Shall I open an issue to discuss this? If you have a better idea please open one instead :)

Yes, open an issue to discuss this.

**Comment by jamwaffles** [comment]
I've opened #329 to discuss.

I think this PR can be closed now as it wasn't a good approach to start with. Please reopen if you disagree!

**Pull request closed without merging**
