### PR TITLE
Revert "Define circles by top-left + diameter instead of center + rad…

### PR DESCRIPTION
**Pull request by jamwaffles**
This reverts the merge of #274 into master so that it may be cherry picked onto a 0.7.0 feature branch. 

Cc #288

### CODE REVIEW

**Comment by jamwaffles** [comment]
@rfuest We should probably merge this before anything else that's currently open.

**Comment by rfuest** [comment]
> @rfuest We should probably merge this before anything else that's currently open.

Yes and I guess we also need to create new PRs, because I don't think there is a way to change the target branch.

**Comment by jamwaffles** [comment]
> I don't think there is a way to change the target branch.

The Github UI allows the base branch of the PR to be changed if that's what you mean.

**Comment by rfuest** [comment]
I just wanted to compare the `revert-breaking-master-change` branch with the `0.6.0` tag, but there is no `0.6.0` tag. The latest tagged version is `beta.2`

**Comment by jamwaffles** [comment]
Huh oh yeah. Let me create one and push it

**Comment by jamwaffles** [comment]
Pushed!

**Pull request merged**
