### PR TITLE
Add more fonts

### PR DESCRIPTION
**Pull request by chocol4te**
This PR adds 3 new fonts: 6x12, 8x16, 12x16.

img_0677

### CODE REVIEW

**Comment by jamwaffles** [comment]
Awesome, thanks! Sorry it took me a while to get to this, got hit by a car a few days ago 😂

LGTM :)

**Comment by jamwaffles** [comment]
#27

**Comment by chocol4te** [comment]
@jamwaffles 😱 Hope you are ok!

**Comment by jamwaffles** [comment]
Just a broken collar bone :)

I forgot to ask; where did you get these fonts from? Uzebox? I just want to make sure the attribution in the readme is correct.

**Comment by chocol4te** [comment]
All from Uzebox.

I’m pretty sure they are mostly scaled copies of the 6x8 and can be removed when matrix transformations are possible

**Comment by jamwaffles** [comment]
Sweet, good point on the scaling, hadn't considered that use case for transforms.

**Pull request merged**
