### PR TITLE
Add support for horizontal and vertical text alignment

### PR DESCRIPTION
**Pull request by aurelj**
Hi! Thank you for helping out with Embedded Graphics development! Please:

- [X] Check that you've added passing tests and documentation
- [X] Add a simulator example(s) where applicable
- [X] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, etc) and appropriate crate (`embedded-graphics`, `simulator`, `tinytga`, `tinybmp`) if your changes affect the **public API**
- [X] Run `rustfmt` on the project
- [X] Run `./build.sh` (Linux/macOS only) and make sure it passes. If you use Windows, check that CI passes once you've opened the PR.

## PR description

Add support for horizontal and vertical text alignment

### CODE REVIEW

**Comment by jamwaffles** [comment]
Thanks for the PR and I appreciate the time you've taken to write this, but this behaviour is outside the scope of fonts/text in e-g. I'd suggest creating your own wrapper struct for layout in your app code. The functionality proposed here would be added by something like a UI/layout library at a higher level, using e-g components as building blocks.

Both I and @rfuest want to take a deeper look at how fonts and text works in 0.7.0 (including whatever comes out of #225 which might help your use case), but I don't think padding like this PR adds will be included in fonts directly.

**Comment by rfuest** [comment]
IMO we should consider adding this in 0.7. Drawing backgrounds this way works much better that our current implementation and this would be useful for simple applications that don't need any higher level UI library.

But it should be implemented as a separate drawable, like `FramedText`, and not mixed in with the current `Text`.

**Comment by aurelj** [comment]
It seemed quite the obvious way to do it, but with your feedback I now totally see that it shouldn't be part of `Text`. I still think it is worth having in embedded-graphics somewhere. `FramedText` sounds like a good idea. Maybe even something more versatile like a `Layout` module that would allow positioning and aligning any kind of entity ?

Oh, and I also perfectly understand that you don't want to include such a change in 0.6, it seems sensible to wait for 0.7.

Anyway, I will put this idea at rest for a bit and think about it again in a few days with a fresh mind.

**Comment by bugadani** [comment]
I've published a preview version of [embedded-text](https://crates.io/crate/embedded-text) that you may find useful @aurelj 
No vertical alignment support yet, though

**Comment by jamwaffles** [comment]
This PR is pretty stale now, and I think `embedded-text` or `embedded-layout` could be good options for better text layout than a simpler solution included in e-g so I'm going to close this PR in lieu of those crates.

**Pull request closed without merging**
