### PR TITLE
Updated projects list

### PR DESCRIPTION
**Pull request by jamwaffles**
Hi! Thank you for helping out with Embedded Graphics development! Please:

- [ ] Check that you've added passing tests and documentation
- [ ] Add a simulator example(s) where applicable
- [ ] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, etc)
- [ ] Run `rustfmt` on the project
- [ ] Run `./build.sh` (Linux/macOS only) and make sure it passes. If you use Windows, check that CI passes once you've opened the PR.

## PR description

* Adds [hub75 driver](https://crates.io/crates/hub75) which has e-g support
* ~Adds version badges next to crates:~
  
  image

  ~After adding them I'm not so sure it's a great idea... thoughts?~

### CODE REVIEW

**Comment by rfuest** [comment]
>     * After adding them I'm not so sure it's a great idea... thoughts?

A table could make the list look nicer, but I'm not sure the version information in necessary at that point. But we should consider splitting the list by drivers that support the current e-g version and ones that are still depending on old versions like 0.4 or even older.

**Comment by jamwaffles** [comment]
I did try a table but Github forces headers which looks weird.

> But we should consider splitting the list by drivers that support the current e-g version and ones that are still depending on old versions like 0.4 or even older.

That's quite a bit of maintenance burden on us to keep it fresh (unless it's automated, but then there are two problems) so I don't think that's sensible.

**Comment by rfuest** [comment]
> I did try a table but Github forces headers which looks weird.

Did you only try with markdown or also with HTML?

> That's quite a bit of maintenance burden on us to keep it fresh (unless it's automated, but then there are two problems) so I don't think that's sensible.

I agree, but from a user perspective it's really annoying if you think there is support for your display and it turns out to be only available for an old unmaintained version of e-g.

**Comment by jamwaffles** [comment]
> Did you only try with markdown or also with HTML?

Just markdown. Tbh I don't think it adds much value showing other crate versions in the readme so I'm going to remove it and make this PR just add the hub75 driver.

> from a user perspective it's really annoying if you think there is support for your display and it turns out to be only available for an old unmaintained version of e-g.

Absolutely, but that's not something I'm willing to maintain, at least at the moment.

**Comment by rfuest** [comment]
> Absolutely, but that's not something I'm willing to maintain, at least at the moment.

Fair enough. How about adding a note that some drivers might not work with the latest e-g version and that this can be checked on crates.io?

**Comment by jamwaffles** [comment]
Good idea. Done!

**Pull request merged**
